package br.edu.ufrgs.service.verifiers;

import br.edu.ufrgs.model.Transaction;

/**
 * Evaluates the commercial category of a transaction to determine its specific risk score.
 * This verifier checks if the merchant belongs to a high-risk segment and flags the 
 * operation accordingly.
 *
 * @author Gabriel Pieruccini Knopp
 * @version 1.1.0
 */
public class CategoryVerifier {

    /**
     * Calculates the risk score based on the transaction's business category.
     * If the transaction belongs to high-risk categories such as "Joalheria", "Eletronicos", 
     * or "Cassino", it adds "Categoria" to the transaction's list of motives and returns 
     * a penalty score of 20. Otherwise, it returns a score of 0.
     *
     * @param action The transaction instance being evaluated.
     * @return An int representing the risk score generated by the category verification 
     *         (20 for high-risk categories, 0 otherwise).
     */
    public static int verifyScore(Transaction action){
        String transactionCategory = action.getCategory();
        if("Joalheria".equals(transactionCategory) || "Eletronicos".equals(transactionCategory) || "Cassino".equals(transactionCategory))
        {
            action.addMotive("Categoria");
            return 20;
        }
        return 0;
    }
}