package br.edu.ufrgs.service.verifiers;

import br.edu.ufrgs.model.Transaction;

/**
 * Evaluates the geographical origin of a transaction to determine its specific risk score.
 * This verifier checks if the operation originated outside the domestic region and flags 
 * it accordingly.
 *
 * @author Gabriel Pieruccini Knopp
 * @version 1.1.0
 */
public class OriginVerifier {
    
    /**
     * Calculates the risk score based on the transaction's country of origin.
     * If the transaction did not originate in "Brasil", it adds "Internacional" 
     * to the transaction's list of motives and returns a penalty score of 30. 
     * Otherwise, it returns a score of 0.
     *
     * @param action The transaction instance being evaluated.
     * @return An int representing the risk score generated by the origin verification 
     *         (30 for international transactions, 0 otherwise).
     */
    public static int verifyScore(Transaction action){
        String transactionOrigin = action.getOrigin();
        if(!"Brasil".equals(transactionOrigin))
        {
            action.addMotive("Internacional");
            return 30;
        }
        return 0;
    }
}