package br.edu.ufrgs.service.verifiers;

import br.edu.ufrgs.model.Transaction;
import java.time.LocalTime;
import java.time.ZonedDateTime;

/**
 * Evaluates the execution time of a transaction to determine its specific risk score.
 * This verifier checks if the operation occurred during critical late-night or 
 * early-morning hours and flags it accordingly.
 *
 * @author Gabriel Pieruccini Knopp
 * @version 1.1.0
 */
public class TimeVerifier {
    
    /**
     * Calculates the risk score based on the transaction's time of execution.
     * If the transaction occurs during the critical window between 23:00 and 05:00, 
     * it adds "Horario" to the transaction's list of motives and returns a penalty 
     * score of 20. Otherwise, it returns a score of 0.
     *
     * @param action The transaction instance being evaluated.
     * @return An int representing the risk score generated by the time verification 
     * (20 for critical hours, 0 otherwise).
     */
    public static int verifyScore(Transaction action){
        ZonedDateTime dateTime = action.getTime();
        LocalTime transactionHour = dateTime.toLocalTime();
        
        LocalTime criticalHoursStart = LocalTime.of(23, 0);
        LocalTime criticalHoursEnd = LocalTime.of(5, 0);

        if (!transactionHour.isBefore(criticalHoursStart) || !transactionHour.isAfter(criticalHoursEnd)) {
            action.addMotive("Horario");
            return 20; 
        }
        
        return 0; 
    }
}