package br.edu.ufrgs.service.verifiers;

import br.edu.ufrgs.model.Transaction;
import java.math.BigDecimal;

/**
 * Evaluates the financial amount of a transaction to determine its specific risk score.
 * This verifier checks if the operation value exceeds a predefined safe threshold and 
 * flags it accordingly.
 *
 * @author Gabriel Pieruccini Knopp
 * @version 1.1.0
 */
public class ValueVerifier {
    
    /**
     * Calculates the risk score based on the transaction's monetary value.
     * If the transaction value is strictly greater than 8000, it adds "Valor" 
     * to the transaction's list of motives and returns a penalty score of 40. 
     * Otherwise, it returns a score of 0.
     *
     * @param action The transaction instance being evaluated.
     * @return An int representing the risk score generated by the value verification 
     *         (40 for values exceeding the threshold, 0 otherwise).
     */
    public static int verifyScore(Transaction action){
        BigDecimal transactionValue = action.getValue();
        BigDecimal minimalStrangeValue = BigDecimal.valueOf(8000);
        if(transactionValue.compareTo(minimalStrangeValue) > 0)
        {
            action.addMotive("Valor"); 
            return 40;
        }
        return 0;
    }
}